# 1. Database Connection
spring.datasource.url=jdbc:mysql://gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/greennest?sslMode=VERIFY_IDENTITY
spring.datasource.username=oPm9e8BieWrryDE.root
spring.datasource.password=eH3iAb8b9c8jX5Cg

# 2. JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# 3. Error Handling (To avoid the ugly White Label Error page)
server.error.include-message=always

# 4. Port (Standard is 8080)
server.port=4000

