# Database Configuration
spring.datasource.url=jdbc:mysql://gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/greennest?useSSL=true&requireSSL=true&verifyServerCertificate=false&allowPublicKeyRetrieval=true&enabledTLSProtocols=TLSv1.2
spring.datasource.username=oPm9e8BieWrryDE.root
spring.datasource.password=eH3iAb8b9c8jX5Cg
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Settings
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Server Port
server.port=8080